server.port: 8081
graphql:
  servlet:
    mapping: /graphql
    enabled: true
    corsEnabled: true

graphiql:
  mapping: /graphiql
  endpoint: /graphql
  enabled: true

spring: 
  data: 
    mongodb: 
      host: localhost
      port: 27017
      database: libray-store